# Generated by Django 4.2.2 on 2023-07-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('roll', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('city', models.CharField(max_length=90)),
                ('tour_place', models.CharField(max_length=90)),
                ('dream', models.CharField(max_length=120)),
                ('college', models.CharField(max_length=150)),
                ('ideology', models.CharField(max_length=90)),
            ],
        ),
    ]
