# Generated by Django 4.2.2 on 2023-07-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_occupation'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pass_date',
            field=models.DateTimeField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
    ]
