# Generated by Django 4.2.2 on 2023-07-24 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_pass_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='pass_date',
        ),
    ]
